# Categorical Variables

In Machine Learning features can be categorised mainly into:
Continous features, which include a range values(hence continous), such features can be age,price etc

Categorical features(Discrete features), which mostly contains no numeric values, here there is no middle ground in variables. such features include gender, Education status etc
The mainly distinction between the two is the analogous to the distinction between classification and regression.

Take a look!
Logistic regression equation.
ŷ = w[0] * x[0] + w[1] * x[1] + ... + w[p] * x[p] + b > 0 here the X variable expect the features in numerical value, so its not idea for categorical features. So what should be done?

# One-Hot Encoding(Dummy Variables) Technique

 The idea behind One-Hot Encoding is to replace a categorical variable with one or more new features that can have the values 0 and 1. A feature is 1 if it has the corresponding value and 0 otherwise. 

In [32]:
#Pandas Implementation
import pandas as pd

data = pd.DataFrame({'Name':['kelvin','Fred','Felix','Elia'],'Education':['Degree','Masters','Phd','Phd']})
display(data)

Education    Name
0    Degree  kelvin
1   Masters    Fred
2       Phd   Felix
3       Phd    Elia

In [33]:
encoded = pd.get_dummies(data,columns=['Education'])
print(encoded)

     Name  Education_Degree  Education_Masters  Education_Phd
0  kelvin                 1                  0              0
1    Fred                 0                  1              0
2   Felix                 0                  0              1
3    Elia                 0                  0              1


In [34]:
display(encoded)

Name  Education_Degree  Education_Masters  Education_Phd
0  kelvin                 1                  0              0
1    Fred                 0                  1              0
2   Felix                 0                  0              1
3    Elia                 0                  0              1

['Degree' 'Masters' 'Phd' 'Phd']


# One-Hot Encoding in Sklearn 

In sklearn to use one-hot-encoder class, first one needs to transform the categorical features into numerical label using the LabelEncoder.Then you can encode the dummy features afterwards using the OneHotEncoder class in Sklearn.

In [37]:
x = data.iloc[:,0].values #taking the 1st column "Education" which is categorical
print(x)

['Degree' 'Masters' 'Phd' 'Phd']


In [38]:
#transforming the string categoricals into numeric label
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
x = labelencoder.fit_transform(x)
print(x)

[0 1 2 2]


As you can see the output above 0 -> "Degree"  1 -> "Masters" 2 -> "Phd"

In [39]:
#Encoding the categorical integers created above using OneHostEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
x = x.reshape(-1,1)
encoded_2 = onehotencoder.fit_transform(x).toarray()
print(encoded_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


# Number can Encode Categoricals

In [40]:
demo_df = pd.DataFrame({'Integer Feature':[0,1,2,1],'Categorical Feature':['socks','fox','socks','box']})

In [41]:
display(demo_df)

Categorical Feature  Integer Feature
0               socks                0
1                 fox                1
2               socks                2
3                 box                1

In [42]:
print(demo_df)

  Categorical Feature  Integer Feature
0               socks                0
1                 fox                1
2               socks                2
3                 box                1


In [43]:
demo_df['Integer Features'] = demo_df['Integer Feature'].astype(str)

In [44]:
pd.get_dummies(demo_df, columns=['Integer Feature','Categorical Feature'])

Integer Features  Integer Feature_0  Integer Feature_1  Integer Feature_2  \
0                0                  1                  0                  0   
1                1                  0                  1                  0   
2                2                  0                  0                  1   
3                1                  0                  1                  0   

   Categorical Feature_box  Categorical Feature_fox  Categorical Feature_socks  
0                        0                        0                          1  
1                        0                        1                          0  
2                        0                        0                          1  
3                        1                        0                          0

References:
1. A. C.Muller and S. Guido "Introduction to Machine Learning with Python"